CONNECTOR_INGEST_QUEUE = "connector_ingest"
NORMALIZE_QUEUE = "normalize"
PERMISSIONS_SYNC_QUEUE = "permissions_sync"
PERSONAL_GRAPH_QUEUE = "personal_graph"
AGGREGATE_CONTEXT_QUEUE = "aggregate_context"

ALL_QUEUES = [
    CONNECTOR_INGEST_QUEUE,
    NORMALIZE_QUEUE,
    PERMISSIONS_SYNC_QUEUE,
    PERSONAL_GRAPH_QUEUE,
    AGGREGATE_CONTEXT_QUEUE,
]
